#!/usr/bin/env node
/**
 * Build script for A11Y Auditor.
 *
 * The analyzers in src/ are written as ES modules (import/export) because
 * that's the most readable way to keep them separate. A bookmarklet,
 * though, has to be a single classic script (no import/export) packaged as
 * `javascript:...`.
 *
 * This script:
 *   1. Reads the classes from src/core and src/analyzers.
 *   2. Strips the `import` / `export default` lines (always full lines at
 *      the top of the file, so removing them is safe).
 *   3. Concatenates everything into a single IIFE together with each
 *      bookmarklet's orchestration logic.
 *   4. Writes the readable result to dist/ and generates
 *      bookmarklets.data.js, which the install page (page/index.html) uses
 *      to build the real `javascript:` links.
 *
 * Usage: node build.js  (or `npm run build`)
 * Requires no npm dependencies.
 */

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const SRC = path.join(__dirname, "src");
const DIST = path.join(__dirname, "dist");
const PAGE = path.join(__dirname, "page");

function readSrc(relativePath) {
  return fs.readFileSync(path.join(SRC, relativePath), "utf8");
}

/**
 * Strips ES module syntax: `import ...;`, `export default X;` (full
 * lines), and the `export ` prefix from named exports (`export const`,
 * `export function`, `export class`) without touching the rest of the
 * declaration.
 */
function stripModuleSyntax(source) {
  return source
    .replace(/^\s*import .*;\s*$/gm, "")
    .replace(/^\s*export default \w+;\s*$/gm, "")
    .replace(/^export (?=const |class |function )/gm, "");
}

function wrapIife(body) {
  return `(function () {\n"use strict";\n${body}\n})();`;
}

function toBookmarkletHref(code) {
  return "javascript:" + encodeURIComponent(code);
}

// --- Main bookmarklet: all the classes + main.js's menu ---
const CORE_FILES = ["core/analyzer.js", "core/ui.js", "core/wcag.js"];
const ANALYZER_FILES = [
  "analyzers/headings.js",
  "analyzers/axeCore.js",
  "analyzers/images.js",
  "analyzers/contrast.js",
  "analyzers/aria.js",
  "analyzers/forms.js",
  "analyzers/semantic.js",
  "analyzers/keyboard.js",
  "analyzers/links.js",
];
const REST_FILES = ["core/auditor.js", "utils/json.js"];

function buildMainBundle() {
  const parts = [...CORE_FILES, ...ANALYZER_FILES, ...REST_FILES].map(
    (file) => stripModuleSyntax(readSrc(file)).trim(),
  );

  const mainLogic = readSrc("bookmarklets/main.js").trim();
  parts.push(mainLogic);

  return wrapIife(parts.join("\n\n"));
}

// --- Individual bookmarklets: already self-contained IIFEs ---
const INDIVIDUAL_BOOKMARKLETS = {
  headings: "bookmarklets/individual/headings.js",
  axe: "bookmarklets/individual/axe.js",
  images: "bookmarklets/individual/images.js",
  contrast: "bookmarklets/individual/contrast.js",
};

function buildIndividualBundle(relativePath) {
  return readSrc(relativePath).trim();
}

/**
 * build.js concatenates several files into a single scope (no modules), so
 * a name clash between analyzers (two identical `const`s) or an
 * incorrectly stripped export line only shows up as a SyntaxError when it
 * runs in the browser. We validate it right here, on every build, instead
 * of discovering it only when testing the bookmarklet by hand.
 */
function assertValidSyntax(code, label) {
  try {
    new vm.Script(code);
  } catch (error) {
    console.error(`✗ ${label} has a syntax error:\n`);
    throw error;
  }
}

function main() {
  fs.mkdirSync(DIST, { recursive: true });

  const bookmarklets = {};

  const mainCode = buildMainBundle();
  assertValidSyntax(mainCode, "main.bookmarklet.js");
  fs.writeFileSync(path.join(DIST, "main.bookmarklet.js"), mainCode);
  bookmarklets.main = {
    name: "A11Y Auditor Main",
    href: toBookmarkletHref(mainCode),
  };

  for (const [key, relativePath] of Object.entries(INDIVIDUAL_BOOKMARKLETS)) {
    const code = buildIndividualBundle(relativePath);
    assertValidSyntax(code, `${key}.bookmarklet.js`);
    fs.writeFileSync(path.join(DIST, `${key}.bookmarklet.js`), code);
    bookmarklets[key] = {
      name: key,
      href: toBookmarkletHref(code),
    };
  }

  const dataFile = `// Auto-generated by build.js — do not edit by hand.
// To regenerate: npm run build
window.A11Y_BOOKMARKLETS = ${JSON.stringify(bookmarklets, null, 2)};
`;
  fs.writeFileSync(path.join(PAGE, "bookmarklets.data.js"), dataFile);

  console.log("✓ Bookmarklets generated in bookmarklets/dist/");
  console.log("✓ bookmarklets/page/bookmarklets.data.js updated");
  for (const [key, { href }] of Object.entries(bookmarklets)) {
    console.log(`  - ${key}: ${(href.length / 1024).toFixed(1)} KB`);
  }
}

main();
